apiVersion: v1
kind: ConfigMap
metadata:
  name: logistics-config
  namespace: logistics-routing
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"
  METRICS_PORT: "9464"
  WEBSOCKET_ENABLED: "true"
  WEBSOCKET_PORT: "3001"
  DELHI_COMPLIANCE_ENABLED: "true"
  ODD_EVEN_ENFORCEMENT: "true"
  POLLUTION_ZONE_ENFORCEMENT: "true"
  TIME_RESTRICTION_ENFORCEMENT: "true"
  PREMIUM_SERVICE_ENABLED: "true"
  LOYALTY_PROGRAM_ENABLED: "true"
  INTERACTIVE_DEMO_ENABLED: "false"
  PERFORMANCE_TESTING_ENABLED: "false"
  DEFAULT_EFFICIENCY_TARGET: "0.20"
  MAX_ROUTE_OPTIMIZATION_TIME: "10000"
  MAX_API_RESPONSE_TIME: "5000"
  CACHE_TTL_VEHICLE_SEARCH: "300"
  CACHE_TTL_TRAFFIC_DATA: "180"
  CACHE_TTL_ROUTE_OPTIMIZATION: "600"
  DATA_RETENTION_DAYS: "365"
  AUDIT_LOG_RETENTION_DAYS: "2555"
  SENSITIVE_DATA_RETENTION_DAYS: "365"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  RATE_LIMIT_SKIP_SUCCESSFUL_REQUESTS: "true"
  ORTOOLS_TIMEOUT: "10000"
  ORTOOLS_MAX_VEHICLES: "100"
  ORTOOLS_MAX_DELIVERIES: "500"
  CORS_ORIGIN: "https://logistics.example.com"
  CORS_CREDENTIALS: "true"